.\" Manpage for ezdb
.\" Contact 0xCB[at]protonmail[dot]com for issues with this document
.TH man 1 "25 may 2018" "0.2.0" "ezdb man page"
.SH NAME
ezdb \- Run the ezdb daemon

.SH DESCRIPTION
ezdb is an in-memory key-value database used primarily for interprocess communication. ezdb is written in the Crystal language.

.SH BUGS
No known bugs

.SH AUTHOR
Carter Brainerd - @cbrnrd - 0xCB[at]protonmail[dot]com

.SH Website
https://carterbrainerd.me/ezdb

.SH Source code
The source code for ezdb is available here: https://github.com/cbrnrd/ezdb
